version: '3'

services:
  couchserver:
    image: couchdb:latest
    restart: always
    ports:
      - "8080:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    volumes:
        - ./couchdb_data:/opt/couchdb/data

  servidor_web:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - couchserver
  
  interfaz_web:
    build:
      context: ./frontend
    ports:
      - "5500:80"
    depends_on:
      - servidor_web

